import type {
  DemandaItem,
  ProjetoItem,
  KanbanTask,
  CronogramaItem,
  OrcamentoCategoria,
  FinancialTransaction,
  TeamMember,
  RaciItem,
  ProjectFileItem,
  AuditEvent,
} from "./types";

// Demanda Inicial Vinculada (DEM-0235)
export const initialDemanda: DemandaItem = {
  id: "dem-0235",
  code: "DEM-0235",
  title: "Modernização e Qualificação do Centro Esportivo Comunitário",
  category: "Infraestrutura Urbana",
  description:
    "Solicitação de reformas estruturais, iluminação de LED, pavimentação das quadras e implantação de acessibilidade no Centro Esportivo.",
  priority: "Alta",
  channelOrigin: "Gabinete Virtual",
  regionId: "reg-1",
  municipio: "São Paulo / SP",
  bairro: "Centro",
  address: "Av. do Esporte, 500",
  cep: "01000-000",
  responsible: "Ana Martins",
  team: "Equipe de Gestão de Projetos",
  status: "Convertida em projeto",
  receiptDate: "2025-06-12",
  analysisDeadline: "2025-06-18",
  applicantName: "Associação de Moradores do Centro",
  applicantPhone: "(11) 97777-6666",
  applicantEmail: "contato@amcentro.org.br",
  files: ["Termo_de_Abertura.docx", "Levantamento_Tecnico.pdf", "Planta_Baixa_Esportes.dwg"],
  hasBudget: true,
  estimatedBudget: 480000,
  budgetSource: "Dotação Orçamentária Municipal / Esportes",
  approvedBy: "Ana Martins",
  approvalDate: "15/06/2025 às 14:00",
  approvalRole: "Coordenadora de Projetos",
  createdAt: "12/06/2025 às 08:30",
  criteria: {
    multDeliveries: true,
    needsTeam: true,
    hasTimeline: true,
    needsBudget: true,
    approvedByResponsible: true,
  },
  technicalReport:
    "Análise técnica realizada e aprovada. Projeto apresenta alta viabilidade técnica e impacto social comunitário relevante.",
  decision: "Aprovada para Projeto",
  decisionJustification:
    "Demanda atende a todos os 5 critérios institucionais e possui dotação orçamentária prévia.",
  convertedProjectId: "prj-0104",
};

// Projeto Ativo (PRJ-0104 - Modernização do Centro Esportivo)
export const initialProjeto: ProjetoItem = {
  id: "prj-0104",
  code: "PRJ-0104",
  title: "Modernização do Centro Esportivo",
  demandaId: "dem-0235",
  demandaCode: "DEM-0235",
  category: "Infraestrutura Urbana",
  responsible: "Ana Martins",
  status: "Em execução",
  priority: "Alta",
  description: "Acompanhe entregas, tarefas, responsáveis, prazos e dependências.",
  startDate: "02/06/2025",
  endDate: "30/09/2025",
  progress: 45,
  createdAt: "18/06/2025 às 08:30",
};

// Tarefas do Kanban (Conforme Imagem de Referência)
export const initialKanbanTasks: KanbanTask[] = [
  // Planejamento
  {
    id: "task-1",
    code: "ETG-016",
    title: "Plano de comunicação do projeto",
    type: "entrega",
    columnId: "planejamento",
    priority: "Média",
    responsible: "Marina Lima",
    responsibleAvatar: "ML",
    dueDate: "15/07/2025",
    progress: 20,
    tags: ["Comunicação"],
    checklistCompleted: 1,
    checklistTotal: 4,
    commentsCount: 3,
    attachmentsCount: 2,
  },
  {
    id: "task-2",
    code: "TAR-041",
    title: "Validar requisitos de acessibilidade",
    type: "tarefa",
    columnId: "planejamento",
    priority: "Alta",
    responsible: "Rafael Pereira",
    responsibleAvatar: "RP",
    dueDate: "20/07/2025",
    progress: 0,
    tags: ["Engenharia", "LGPD"],
    checklistCompleted: 0,
    checklistTotal: 3,
    commentsCount: 1,
    attachmentsCount: 1,
  },

  // A fazer
  {
    id: "task-3",
    code: "TAR-035",
    title: "Contratar levantamento técnico",
    type: "tarefa",
    columnId: "afazer",
    priority: "Alta",
    responsible: "Rafael Pereira",
    responsibleAvatar: "RP",
    dueDate: "01/08/2025",
    progress: 10,
    tags: ["Contratação"],
    checklistCompleted: 1,
    checklistTotal: 5,
    commentsCount: 4,
    attachmentsCount: 3,
  },
  {
    id: "task-4",
    code: "ETG-012",
    title: "Plano de ação e orçamento",
    type: "entrega",
    columnId: "afazer",
    priority: "Alta",
    responsible: "Carlos Souza",
    responsibleAvatar: "CS",
    dueDate: "10/06/2025",
    progress: 15,
    tags: ["Financeiro"],
    checklistCompleted: 2,
    checklistTotal: 6,
    commentsCount: 5,
    attachmentsCount: 4,
  },
  {
    id: "task-5",
    code: "TAR-038",
    title: "Agendar reunião com parceiros",
    type: "tarefa",
    columnId: "afazer",
    priority: "Média",
    responsible: "Ana Paula",
    responsibleAvatar: "AP",
    dueDate: "25/07/2025",
    progress: 0,
    tags: ["Parceiros"],
    checklistCompleted: 0,
    checklistTotal: 2,
    commentsCount: 2,
    attachmentsCount: 0,
  },

  // Em execução
  {
    id: "task-6",
    code: "ETG-009",
    title: "Diagnóstico e levantamento técnico",
    type: "entrega",
    columnId: "execucao",
    priority: "Alta",
    responsible: "Rafael Pereira",
    responsibleAvatar: "RP",
    dueDate: "18/07/2025",
    progress: 65,
    tags: ["Vistoria"],
    checklistCompleted: 4,
    checklistTotal: 6,
    commentsCount: 8,
    attachmentsCount: 5,
  },
  {
    id: "task-7",
    code: "TAR-029",
    title: "Mapear fornecedores locais",
    type: "tarefa",
    columnId: "execucao",
    priority: "Média",
    responsible: "Ana Paula",
    responsibleAvatar: "AP",
    dueDate: "11/07/2025",
    progress: 60,
    tags: ["Suprimentos"],
    checklistCompleted: 3,
    checklistTotal: 4,
    commentsCount: 2,
    attachmentsCount: 1,
  },
  {
    id: "task-8",
    code: "TAR-031",
    title: "Preparar documentação técnica",
    type: "tarefa",
    columnId: "execucao",
    priority: "Alta",
    responsible: "João Victor",
    responsibleAvatar: "JV",
    dueDate: "14/07/2025",
    progress: 50,
    tags: ["Documentação"],
    checklistCompleted: 2,
    checklistTotal: 4,
    commentsCount: 3,
    attachmentsCount: 2,
  },

  // Em validação
  {
    id: "task-9",
    code: "ETG-007",
    title: "Projeto arquitetônico preliminar",
    type: "entrega",
    columnId: "validacao",
    priority: "Urgente",
    responsible: "João Victor",
    responsibleAvatar: "JV",
    dueDate: "18/07/2025",
    progress: 90,
    tags: ["Arquitetura"],
    checklistCompleted: 5,
    checklistTotal: 5,
    commentsCount: 12,
    attachmentsCount: 6,
  },
  {
    id: "task-10",
    code: "TAR-024",
    title: "Conferência da documentação",
    type: "tarefa",
    columnId: "validacao",
    priority: "Média",
    responsible: "Ana Martins",
    responsibleAvatar: "AM",
    dueDate: "22/07/2025",
    progress: 85,
    tags: ["Revisão"],
    checklistCompleted: 4,
    checklistTotal: 4,
    commentsCount: 4,
    attachmentsCount: 2,
  },

  // Concluídas
  {
    id: "task-11",
    code: "MAR-003",
    title: "Aprovação do termo de abertura",
    type: "marco",
    columnId: "concluidas",
    priority: "Alta",
    responsible: "Ana Martins",
    responsibleAvatar: "AM",
    dueDate: "04/06/2025",
    progress: 100,
    tags: ["Aprovação"],
    checklistCompleted: 3,
    checklistTotal: 3,
    commentsCount: 6,
    attachmentsCount: 3,
  },
  {
    id: "task-12",
    code: "TAR-018",
    title: "Definição da equipe do projeto",
    type: "tarefa",
    columnId: "concluidas",
    priority: "Média",
    responsible: "Ana Martins",
    responsibleAvatar: "AM",
    dueDate: "09/06/2025",
    progress: 100,
    tags: ["Equipe"],
    checklistCompleted: 4,
    checklistTotal: 4,
    commentsCount: 3,
    attachmentsCount: 1,
  },
  {
    id: "task-13",
    code: "ETG-004",
    title: "Levantamento das necessidades",
    type: "entrega",
    columnId: "concluidas",
    priority: "Alta",
    responsible: "Rafael Pereira",
    responsibleAvatar: "RP",
    dueDate: "27/06/2025",
    progress: 100,
    tags: ["Diagnóstico"],
    checklistCompleted: 5,
    checklistTotal: 5,
    commentsCount: 7,
    attachmentsCount: 4,
  },
];

// Dados do Cronograma / Gantt (Conforme Imagem 4)
export const initialCronogramaData: CronogramaItem[] = [
  {
    id: "phase-1",
    name: "1. Fase 1 — Planejamento",
    responsible: "Ana Paula",
    startDate: "02/06",
    endDate: "13/06",
    progress: 100,
    status: "Concluída",
    level: 1,
    children: [
      {
        id: "c-1",
        code: "MAR-003",
        name: "Termo de abertura",
        responsible: "Ana Paula",
        startDate: "02/06",
        endDate: "04/06",
        progress: 100,
        status: "Concluída",
        isMilestone: true,
        level: 2,
      },
      {
        id: "c-2",
        code: "TAR-018",
        name: "Definição da equipe",
        responsible: "Ana Paula",
        startDate: "05/06",
        endDate: "09/06",
        progress: 100,
        status: "Concluída",
        level: 2,
      },
      {
        id: "c-3",
        code: "ETG-016",
        name: "Plano de comunicação",
        responsible: "João Victor",
        startDate: "09/06",
        endDate: "13/06",
        progress: 100,
        status: "Concluída",
        level: 2,
      },
    ],
  },
  {
    id: "phase-2",
    name: "2. Fase 2 — Diagnóstico técnico",
    responsible: "Ana Martins",
    startDate: "16/06",
    endDate: "18/07",
    progress: 65,
    status: "Em andamento",
    level: 1,
    children: [
      {
        id: "c-4",
        code: "ETG-004",
        name: "Levantamento das necessidades",
        responsible: "Ana Martins",
        startDate: "16/06",
        endDate: "27/06",
        progress: 100,
        status: "Concluída",
        level: 2,
      },
      {
        id: "c-5",
        code: "TAR-029",
        name: "Mapeamento de fornecedores",
        responsible: "Rafael Pereira",
        startDate: "30/06",
        endDate: "11/07",
        progress: 60,
        status: "Em andamento",
        level: 2,
      },
      {
        id: "c-6",
        code: "ETG-007",
        name: "Projeto arquitetônico preliminar",
        responsible: "João Victor",
        startDate: "14/07",
        endDate: "18/07",
        progress: 20,
        status: "Atrasada",
        level: 2,
      },
    ],
  },
  {
    id: "phase-3",
    name: "3. Fase 3 — Execução",
    responsible: "Ana Martins",
    startDate: "21/07",
    endDate: "29/08",
    progress: 25,
    status: "Em andamento",
    level: 1,
    children: [
      {
        id: "c-7",
        code: "TAR-035",
        name: "Contratação do levantamento técnico",
        responsible: "Rafael Pereira",
        startDate: "21/07",
        endDate: "01/08",
        progress: 50,
        status: "Em andamento",
        level: 2,
      },
      {
        id: "c-8",
        code: "ETG-009",
        name: "Adequações estruturais",
        responsible: "Rafael Pereira",
        startDate: "04/08",
        endDate: "15/08",
        progress: 10,
        status: "Crítica",
        level: 2,
      },
      {
        id: "c-9",
        code: "TAR-031",
        name: "Aquisição de equipamentos",
        responsible: "Ana Martins",
        startDate: "18/08",
        endDate: "18/07",
        progress: 0,
        status: "Futura",
        level: 2,
      },
    ],
  },
  {
    id: "phase-4",
    name: "4. Fase 4 — Validação e encerramento",
    responsible: "Ana Paula",
    startDate: "01/09",
    endDate: "30/09",
    progress: 0,
    status: "Futura",
    level: 1,
    children: [
      {
        id: "c-10",
        code: "TAR-024",
        name: "Vistoria final",
        responsible: "Ana Martins",
        startDate: "01/09",
        endDate: "12/09",
        progress: 0,
        status: "Futura",
        level: 2,
      },
      {
        id: "c-11",
        code: "ETG-012",
        name: "Aprovação das entregas",
        responsible: "João Victor",
        startDate: "15/09",
        endDate: "24/09",
        progress: 0,
        status: "Futura",
        level: 2,
      },
      {
        id: "c-12",
        code: "MAR-005",
        name: "Encerramento do projeto",
        responsible: "Ana Paula",
        startDate: "25/09",
        endDate: "30/09",
        progress: 0,
        status: "Futura",
        isMilestone: true,
        level: 2,
      },
    ],
  },
];

// Categorias do Orçamento (Conforme Imagem 3)
export const initialOrcamentoCategorias: OrcamentoCategoria[] = [
  {
    id: "cat-1",
    name: "Obras e infraestrutura",
    planned: 240000,
    committed: 172800,
    paid: 86400,
    balance: 67200,
    utilization: 72,
    color: "#00A978",
  },
  {
    id: "cat-2",
    name: "Equipamentos",
    planned: 100000,
    committed: 45000,
    paid: 22500,
    balance: 55000,
    utilization: 45,
    color: "#1264F3",
  },
  {
    id: "cat-3",
    name: "Serviços técnicos",
    planned: 70000,
    committed: 28600,
    paid: 16100,
    balance: 41400,
    utilization: 41,
    color: "#7928F5",
  },
  {
    id: "cat-4",
    name: "Comunicação",
    planned: 30000,
    committed: 8500,
    paid: 3800,
    balance: 21500,
    utilization: 28,
    color: "#F59E0B",
  },
  {
    id: "cat-5",
    name: "Reserva de contingência",
    planned: 40000,
    committed: 27500,
    paid: 28000,
    balance: 12000,
    utilization: 70,
    color: "#00C49F",
  },
];

// Movimentações Financeiras (Conforme Imagem 3)
export const initialFinancialTransactions: FinancialTransaction[] = [
  {
    id: "tx-1",
    date: "28/05/2025",
    document: "NF-2025-1587",
    description: "Execução de fundação - Bloco A",
    supplier: "Construtora Horizonte Ltda.",
    category: "Obras e infraestrutura",
    value: 68500.0,
    status: "Pago",
  },
  {
    id: "tx-2",
    date: "27/05/2025",
    document: "ORC-2025-0921",
    description: "Aquisição de equipamentos esportivos",
    supplier: "Sport Equipamentos",
    category: "Equipamentos",
    value: 32000.0,
    status: "Aguardando aprovação",
  },
  {
    id: "tx-3",
    date: "24/05/2025",
    document: "CT-2025-044",
    description: "Consultoria técnica especializada",
    supplier: "Engenharia & Projetos",
    category: "Serviços técnicos",
    value: 18300.0,
    status: "Comprometido",
  },
  {
    id: "tx-4",
    date: "20/05/2025",
    document: "NF-2025-1145",
    description: "Material de comunicação visual",
    supplier: "Visual Impacto Gráfica",
    category: "Comunicação",
    value: 4850.0,
    status: "Pago",
  },
  {
    id: "tx-5",
    date: "18/05/2025",
    document: "NF-2025-0978",
    description: "Serviços de terraplanagem",
    supplier: "Terraplanagem São José",
    category: "Obras e infraestrutura",
    value: 21000.0,
    status: "Rejeitado",
  },
];

// Integrantes da Equipe (Conforme Imagem 2)
export const initialTeamMembers: TeamMember[] = [
  {
    id: "tm-1",
    name: "Ana Martins",
    role: "Gerente do projeto",
    department: "Gestão de Projetos",
    status: "Disponível",
    tasksCount: 4,
    allocationPercent: 90,
    avatarInitials: "AM",
    avatarBg: "bg-[#008B63]",
  },
  {
    id: "tm-2",
    name: "Rafael Pereira",
    role: "Responsável técnico",
    department: "Engenharia",
    status: "Disponível",
    tasksCount: 3,
    allocationPercent: 100,
    avatarInitials: "RP",
    avatarBg: "bg-[#1264F3]",
  },
  {
    id: "tm-3",
    name: "João Victor",
    role: "Revisor",
    department: "Qualidade",
    status: "Sobrecarga",
    tasksCount: 3,
    allocationPercent: 120,
    avatarInitials: "JV",
    avatarBg: "bg-[#7928F5]",
  },
  {
    id: "tm-4",
    name: "Ana Paula",
    role: "Analista",
    department: "Planejamento",
    status: "Disponível",
    tasksCount: 2,
    allocationPercent: 75,
    avatarInitials: "AP",
    avatarBg: "bg-[#00A978]",
  },
  {
    id: "tm-5",
    name: "Carlos Souza",
    role: "Financeiro",
    department: "Financeiro",
    status: "Disponível",
    tasksCount: 1,
    allocationPercent: 60,
    avatarInitials: "CS",
    avatarBg: "bg-[#F59E0B]",
  },
  {
    id: "tm-6",
    name: "Marina Lima",
    role: "Comunicação",
    department: "Comunicação",
    status: "Disponível",
    tasksCount: 0,
    allocationPercent: 40,
    avatarInitials: "ML",
    avatarBg: "bg-[#EF4444]",
  },
];

// Matriz RACI (Conforme Imagem 2)
export const initialRaciItems: RaciItem[] = [
  {
    id: "raci-1",
    deliveryCode: "ETG-007",
    deliveryName: "Projeto arquitetônico preliminar",
    responsible: "João Victor",
    approver: "Ana Martins",
    consulted: ["RP", "AP"],
    informed: ["CS", "ML"],
    dueDate: "22/06/2025",
  },
  {
    id: "raci-2",
    deliveryCode: "ETG-016",
    deliveryName: "Plano de comunicação do projeto",
    responsible: "Marina Lima",
    approver: "Ana Martins",
    consulted: ["RP", "AP"],
    informed: ["RP", "CS"],
    dueDate: "15/07/2025",
  },
  {
    id: "raci-3",
    deliveryCode: "ETG-012",
    deliveryName: "Plano de ação e orçamento",
    responsible: "Carlos Souza",
    approver: "Ana Martins",
    consulted: ["RP", "AP"],
    informed: ["JV", "ML"],
    dueDate: "10/06/2025",
  },
  {
    id: "raci-4",
    deliveryCode: "ETG-018",
    deliveryName: "Definição da equipe do projeto",
    responsible: "Ana Martins",
    approver: "Ana Martins",
    consulted: ["RP", "AP"],
    informed: ["CS", "ML"],
    dueDate: "25/05/2025",
  },
  {
    id: "raci-5",
    deliveryCode: "ETG-004",
    deliveryName: "Levantamento das necessidades",
    responsible: "Rafael Pereira",
    approver: "Ana Martins",
    consulted: ["JV", "AP"],
    informed: ["CS", "ML"],
    dueDate: "12/05/2025",
  },
];

// Lista de Arquivos do Projeto (Conforme Imagem 5)
export const initialProjectFiles: ProjectFileItem[] = [
  {
    id: "file-1",
    name: "Projeto arquitetônico preliminar.pdf",
    type: "PDF",
    size: "4,2 MB",
    folder: "Documentos técnicos",
    linkedItem: "ETG-007",
    responsible: "João Victor",
    version: "v3",
    modifiedAt: "22/06/2025 10:15",
    verified: true,
    versionsHistory: [
      { version: "v3", modifiedAt: "22/06/2025 10:15", responsible: "João Victor", size: "4,2 MB", isCurrent: true },
      { version: "v2", modifiedAt: "18/06/2025 09:40", responsible: "Rafael Pereira", size: "1,9 MB" },
      { version: "v1", modifiedAt: "15/06/2025 16:22", responsible: "João Victor", size: "1,7 MB" },
    ],
  },
  {
    id: "file-2",
    name: "Levantamento técnico.xlsx",
    type: "XLSX",
    size: "1,8 MB",
    folder: "Documentos técnicos",
    linkedItem: "TAR-035",
    responsible: "Rafael Pereira",
    version: "v2",
    modifiedAt: "18/06/2025 09:40",
    verified: true,
    versionsHistory: [
      { version: "v2", modifiedAt: "18/06/2025 09:40", responsible: "Rafael Pereira", size: "1,8 MB", isCurrent: true },
    ],
  },
  {
    id: "file-3",
    name: "Termo de abertura.docx",
    type: "DOCX",
    size: "320 KB",
    folder: "Contratos",
    linkedItem: "MAR-003",
    responsible: "Ana Paula",
    version: "v1",
    modifiedAt: "15/06/2025 16:22",
    verified: true,
    versionsHistory: [
      { version: "v1", modifiedAt: "15/06/2025 16:22", responsible: "Ana Paula", size: "320 KB", isCurrent: true },
    ],
  },
  {
    id: "file-4",
    name: "Planta do centro esportivo.dwg",
    type: "DWG",
    size: "12,6 MB",
    folder: "Documentos técnicos",
    linkedItem: "ETG-012",
    responsible: "Ana Martins",
    version: "v1",
    modifiedAt: "12/06/2025 11:08",
    verified: true,
    versionsHistory: [
      { version: "v1", modifiedAt: "12/06/2025 11:08", responsible: "Ana Martins", size: "12,6 MB", isCurrent: true },
    ],
  },
  {
    id: "file-5",
    name: "Relatório fotográfico.zip",
    type: "ZIP",
    size: "28,7 MB",
    folder: "Relatórios",
    linkedItem: "TAR-018",
    responsible: "Rafael Pereira",
    version: "v2",
    modifiedAt: "10/06/2025 14:55",
    verified: true,
    versionsHistory: [
      { version: "v2", modifiedAt: "10/06/2025 14:55", responsible: "Rafael Pereira", size: "28,7 MB", isCurrent: true },
    ],
  },
];

// Eventos do Histórico e Auditoria (Conforme Imagem 1)
export const initialAuditEvents: AuditEvent[] = [
  {
    id: "evt-84",
    time: "09:15",
    dateGroup: "Hoje",
    user: "Ana Martins",
    avatarInitials: "AM",
    avatarBg: "bg-[#008B63]",
    actionText: 'moveu TAR-035 de "A fazer" para "Em execução"',
    eventType: "Tarefa",
    targetCode: "TAR-035",
    targetTitle: "Contratar levantamento técnico",
    previousValue: "Status: A fazer",
    newValue: "Status: Em execução",
    justification: "Início da execução da tarefa após validação do contrato com fornecedor.",
    isImportant: true,
    fullDate: "16/06/2025 às 09:15",
  },
  {
    id: "evt-83",
    time: "08:42",
    dateGroup: "Hoje",
    user: "João Victor",
    avatarInitials: "JV",
    avatarBg: "bg-[#7928F5]",
    actionText: "solicitou ajustes em ETG-007",
    eventType: "Aprovação",
    targetCode: "ETG-007",
    targetTitle: "Projeto arquitetônico preliminar",
    previousValue: "Status: Em validação",
    newValue: "Status: Ajustes solicitados",
    justification: "Revisão de acessibilidade necessária na rampa lateral.",
    isImportant: true,
    fullDate: "16/06/2025 às 08:42",
  },
  {
    id: "evt-82",
    time: "08:10",
    dateGroup: "Hoje",
    user: "Rafael Pereira",
    avatarInitials: "RP",
    avatarBg: "bg-[#1264F3]",
    actionText: 'anexou "Levantamento técnico.xlsx"',
    eventType: "Arquivo",
    targetCode: "ETG-009",
    targetTitle: "Diagnóstico e levantamento técnico",
    previousValue: "Arquivos: 4",
    newValue: "Arquivos: 5",
    justification: "Inclusão de laudo atualizado do solo.",
    isImportant: false,
    fullDate: "16/06/2025 às 08:10",
  },
  {
    id: "evt-81",
    time: "07:28",
    dateGroup: "Hoje",
    user: "Carlos Souza",
    avatarInitials: "CS",
    avatarBg: "bg-[#F59E0B]",
    actionText: "registrou despesa de R$ 24.800,00",
    eventType: "Orçamento",
    targetCode: "DESP-1245",
    targetTitle: "Contratação de consultoria técnica",
    previousValue: "Comprometido: R$ 157.600,00",
    newValue: "Comprometido: R$ 182.400,00",
    justification: "Pagamento de parcela inicial do projeto executivo.",
    isImportant: true,
    fullDate: "16/06/2025 às 07:28",
  },
  {
    id: "evt-80",
    time: "16:45",
    dateGroup: "Ontem",
    user: "Ana Paula",
    avatarInitials: "AP",
    avatarBg: "bg-[#00A978]",
    actionText: "alterou o prazo da TAR-029",
    eventType: "Prazo",
    targetCode: "TAR-029",
    targetTitle: "Mapear fornecedores locais",
    previousValue: "Prazo: 05/07/2025",
    newValue: "Prazo: 11/07/2025",
    justification: "Dilação de prazo aprovada devido ao feriado regional.",
    isImportant: false,
    fullDate: "15/06/2025 às 16:45",
  },
  {
    id: "evt-79",
    time: "15:30",
    dateGroup: "Ontem",
    user: "Sistema",
    avatarInitials: "SIS",
    avatarBg: "bg-[#06284F]",
    actionText: "atualizou o progresso geral de 40% para 45%",
    eventType: "Sistema",
    targetCode: "PRJ-0104",
    targetTitle: "Progresso geral do projeto",
    previousValue: "Progresso: 40%",
    newValue: "Progresso: 45%",
    justification: "Cálculo automático acionado pela entrega da tarefa TAR-018.",
    isImportant: false,
    fullDate: "15/06/2025 às 15:30",
  },
  {
    id: "evt-78",
    time: "10:05",
    dateGroup: "12 de junho de 2025",
    user: "Sistema",
    avatarInitials: "SIS",
    avatarBg: "bg-[#06284F]",
    actionText: "Projeto PRJ-0104 foi criado a partir da demanda DEM-0235",
    eventType: "Sistema",
    targetCode: "DEM-0235",
    targetTitle: "Criação do projeto com status Planejamento",
    previousValue: "Status Demanda: Em análise",
    newValue: "Status Demanda: Convertida em projeto",
    justification: "Transação de conversão concluída com 5 critérios validados.",
    isImportant: true,
    fullDate: "12/06/2025 às 10:05",
  },
];
